/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.appuntivari.forum.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.appuntivari.forum.model.ForumCategory;
import net.appuntivari.forum.service.ForumCategoryLocalServiceUtil;

/**
 * The extended model base implementation for the ForumCategory service. Represents a row in the &quot;PW_ForumCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ForumCategoryImpl}.
 * </p>
 *
 * @author Pasturenzi Francesco
 * @see ForumCategoryImpl
 * @see net.appuntivari.forum.model.ForumCategory
 * @generated
 */
public abstract class ForumCategoryBaseImpl extends ForumCategoryModelImpl
	implements ForumCategory {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a forum category model instance should use the {@link ForumCategory} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			ForumCategoryLocalServiceUtil.addForumCategory(this);
		}
		else {
			ForumCategoryLocalServiceUtil.updateForumCategory(this);
		}
	}
}