/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.appuntivari.forum.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.appuntivari.forum.model.ForumUser;
import net.appuntivari.forum.model.ForumUserModel;
import net.appuntivari.forum.model.ForumUserSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ForumUser service. Represents a row in the &quot;PW_ForumUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.appuntivari.forum.model.ForumUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ForumUserImpl}.
 * </p>
 *
 * @author Pasturenzi Francesco
 * @see ForumUserImpl
 * @see net.appuntivari.forum.model.ForumUser
 * @see net.appuntivari.forum.model.ForumUserModel
 * @generated
 */
@JSON(strict = true)
public class ForumUserModelImpl extends BaseModelImpl<ForumUser>
	implements ForumUserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a forum user model instance should use the {@link net.appuntivari.forum.model.ForumUser} interface instead.
	 */
	public static final String TABLE_NAME = "PW_ForumUser";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_forum_user", Types.BIGINT },
			{ "id_forum", Types.BIGINT },
			{ "user_id", Types.BIGINT },
			{ "status", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table PW_ForumUser (id_forum_user LONG not null primary key,id_forum LONG,user_id LONG,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table PW_ForumUser";
	public static final String ORDER_BY_JPQL = " ORDER BY forumUser.id_forum_user ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PW_ForumUser.id_forum_user ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.net.appuntivari.forum.model.ForumUser"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.net.appuntivari.forum.model.ForumUser"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.net.appuntivari.forum.model.ForumUser"),
			true);
	public static long ID_FORUM_COLUMN_BITMASK = 1L;
	public static long STATUS_COLUMN_BITMASK = 2L;
	public static long USER_ID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ForumUser toModel(ForumUserSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ForumUser model = new ForumUserImpl();

		model.setId_forum_user(soapModel.getId_forum_user());
		model.setId_forum(soapModel.getId_forum());
		model.setUser_id(soapModel.getUser_id());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ForumUser> toModels(ForumUserSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ForumUser> models = new ArrayList<ForumUser>(soapModels.length);

		for (ForumUserSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.net.appuntivari.forum.model.ForumUser"));

	public ForumUserModelImpl() {
	}

	public long getPrimaryKey() {
		return _id_forum_user;
	}

	public void setPrimaryKey(long primaryKey) {
		setId_forum_user(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id_forum_user);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ForumUser.class;
	}

	public String getModelClassName() {
		return ForumUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_forum_user", getId_forum_user());
		attributes.put("id_forum", getId_forum());
		attributes.put("user_id", getUser_id());
		attributes.put("status", getStatus());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_forum_user = (Long)attributes.get("id_forum_user");

		if (id_forum_user != null) {
			setId_forum_user(id_forum_user);
		}

		Long id_forum = (Long)attributes.get("id_forum");

		if (id_forum != null) {
			setId_forum(id_forum);
		}

		Long user_id = (Long)attributes.get("user_id");

		if (user_id != null) {
			setUser_id(user_id);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	public long getId_forum_user() {
		return _id_forum_user;
	}

	public void setId_forum_user(long id_forum_user) {
		_columnBitmask = -1L;

		_id_forum_user = id_forum_user;
	}

	@JSON
	public long getId_forum() {
		return _id_forum;
	}

	public void setId_forum(long id_forum) {
		_columnBitmask |= ID_FORUM_COLUMN_BITMASK;

		if (!_setOriginalId_forum) {
			_setOriginalId_forum = true;

			_originalId_forum = _id_forum;
		}

		_id_forum = id_forum;
	}

	public long getOriginalId_forum() {
		return _originalId_forum;
	}

	@JSON
	public long getUser_id() {
		return _user_id;
	}

	public void setUser_id(long user_id) {
		_columnBitmask |= USER_ID_COLUMN_BITMASK;

		if (!_setOriginalUser_id) {
			_setOriginalUser_id = true;

			_originalUser_id = _user_id;
		}

		_user_id = user_id;
	}

	public long getOriginalUser_id() {
		return _originalUser_id;
	}

	@JSON
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	public void setStatus(String status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (_originalStatus == null) {
			_originalStatus = _status;
		}

		_status = status;
	}

	public String getOriginalStatus() {
		return GetterUtil.getString(_originalStatus);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ForumUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ForumUser toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ForumUser)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public ForumUser toUnescapedModel() {
		return (ForumUser)this;
	}

	@Override
	public Object clone() {
		ForumUserImpl forumUserImpl = new ForumUserImpl();

		forumUserImpl.setId_forum_user(getId_forum_user());
		forumUserImpl.setId_forum(getId_forum());
		forumUserImpl.setUser_id(getUser_id());
		forumUserImpl.setStatus(getStatus());

		forumUserImpl.resetOriginalValues();

		return forumUserImpl;
	}

	public int compareTo(ForumUser forumUser) {
		int value = 0;

		if (getId_forum_user() < forumUser.getId_forum_user()) {
			value = -1;
		}
		else if (getId_forum_user() > forumUser.getId_forum_user()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ForumUser)) {
			return false;
		}

		ForumUser forumUser = (ForumUser)obj;

		long primaryKey = forumUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ForumUserModelImpl forumUserModelImpl = this;

		forumUserModelImpl._originalId_forum = forumUserModelImpl._id_forum;

		forumUserModelImpl._setOriginalId_forum = false;

		forumUserModelImpl._originalUser_id = forumUserModelImpl._user_id;

		forumUserModelImpl._setOriginalUser_id = false;

		forumUserModelImpl._originalStatus = forumUserModelImpl._status;

		forumUserModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ForumUser> toCacheModel() {
		ForumUserCacheModel forumUserCacheModel = new ForumUserCacheModel();

		forumUserCacheModel.id_forum_user = getId_forum_user();

		forumUserCacheModel.id_forum = getId_forum();

		forumUserCacheModel.user_id = getUser_id();

		forumUserCacheModel.status = getStatus();

		String status = forumUserCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			forumUserCacheModel.status = null;
		}

		return forumUserCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id_forum_user=");
		sb.append(getId_forum_user());
		sb.append(", id_forum=");
		sb.append(getId_forum());
		sb.append(", user_id=");
		sb.append(getUser_id());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("net.appuntivari.forum.model.ForumUser");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_forum_user</column-name><column-value><![CDATA[");
		sb.append(getId_forum_user());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_forum</column-name><column-value><![CDATA[");
		sb.append(getId_forum());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>user_id</column-name><column-value><![CDATA[");
		sb.append(getUser_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ForumUser.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ForumUser.class
		};
	private long _id_forum_user;
	private long _id_forum;
	private long _originalId_forum;
	private boolean _setOriginalId_forum;
	private long _user_id;
	private long _originalUser_id;
	private boolean _setOriginalUser_id;
	private String _status;
	private String _originalStatus;
	private long _columnBitmask;
	private ForumUser _escapedModel;
}