/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.appuntivari.forum.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.appuntivari.forum.model.Forum;
import net.appuntivari.forum.model.ForumModel;
import net.appuntivari.forum.model.ForumSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Forum service. Represents a row in the &quot;PW_Forum&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.appuntivari.forum.model.ForumModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ForumImpl}.
 * </p>
 *
 * @author Pasturenzi Francesco
 * @see ForumImpl
 * @see net.appuntivari.forum.model.Forum
 * @see net.appuntivari.forum.model.ForumModel
 * @generated
 */
@JSON(strict = true)
public class ForumModelImpl extends BaseModelImpl<Forum> implements ForumModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a forum model instance should use the {@link net.appuntivari.forum.model.Forum} interface instead.
	 */
	public static final String TABLE_NAME = "PW_Forum";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_forum", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "timestamp", Types.TIMESTAMP },
			{ "company_id", Types.BIGINT },
			{ "create_user_id", Types.BIGINT },
			{ "status", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table PW_Forum (id_forum LONG not null primary key,description VARCHAR(75) null,timestamp DATE null,company_id LONG,create_user_id LONG,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table PW_Forum";
	public static final String ORDER_BY_JPQL = " ORDER BY forum.id_forum DESC";
	public static final String ORDER_BY_SQL = " ORDER BY PW_Forum.id_forum DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.net.appuntivari.forum.model.Forum"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.net.appuntivari.forum.model.Forum"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.net.appuntivari.forum.model.Forum"),
			true);
	public static long COMPANY_ID_COLUMN_BITMASK = 1L;
	public static long CREATE_USER_ID_COLUMN_BITMASK = 2L;
	public static long STATUS_COLUMN_BITMASK = 4L;
	public static long TIMESTAMP_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Forum toModel(ForumSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Forum model = new ForumImpl();

		model.setId_forum(soapModel.getId_forum());
		model.setDescription(soapModel.getDescription());
		model.setTimestamp(soapModel.getTimestamp());
		model.setCompany_id(soapModel.getCompany_id());
		model.setCreate_user_id(soapModel.getCreate_user_id());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Forum> toModels(ForumSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Forum> models = new ArrayList<Forum>(soapModels.length);

		for (ForumSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.net.appuntivari.forum.model.Forum"));

	public ForumModelImpl() {
	}

	public long getPrimaryKey() {
		return _id_forum;
	}

	public void setPrimaryKey(long primaryKey) {
		setId_forum(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id_forum);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Forum.class;
	}

	public String getModelClassName() {
		return Forum.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_forum", getId_forum());
		attributes.put("description", getDescription());
		attributes.put("timestamp", getTimestamp());
		attributes.put("company_id", getCompany_id());
		attributes.put("create_user_id", getCreate_user_id());
		attributes.put("status", getStatus());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_forum = (Long)attributes.get("id_forum");

		if (id_forum != null) {
			setId_forum(id_forum);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Date timestamp = (Date)attributes.get("timestamp");

		if (timestamp != null) {
			setTimestamp(timestamp);
		}

		Long company_id = (Long)attributes.get("company_id");

		if (company_id != null) {
			setCompany_id(company_id);
		}

		Long create_user_id = (Long)attributes.get("create_user_id");

		if (create_user_id != null) {
			setCreate_user_id(create_user_id);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	public long getId_forum() {
		return _id_forum;
	}

	public void setId_forum(long id_forum) {
		_columnBitmask = -1L;

		_id_forum = id_forum;
	}

	@JSON
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	public Date getTimestamp() {
		return _timestamp;
	}

	public void setTimestamp(Date timestamp) {
		_columnBitmask |= TIMESTAMP_COLUMN_BITMASK;

		if (_originalTimestamp == null) {
			_originalTimestamp = _timestamp;
		}

		_timestamp = timestamp;
	}

	public Date getOriginalTimestamp() {
		return _originalTimestamp;
	}

	@JSON
	public long getCompany_id() {
		return _company_id;
	}

	public void setCompany_id(long company_id) {
		_columnBitmask |= COMPANY_ID_COLUMN_BITMASK;

		if (!_setOriginalCompany_id) {
			_setOriginalCompany_id = true;

			_originalCompany_id = _company_id;
		}

		_company_id = company_id;
	}

	public long getOriginalCompany_id() {
		return _originalCompany_id;
	}

	@JSON
	public long getCreate_user_id() {
		return _create_user_id;
	}

	public void setCreate_user_id(long create_user_id) {
		_columnBitmask |= CREATE_USER_ID_COLUMN_BITMASK;

		if (!_setOriginalCreate_user_id) {
			_setOriginalCreate_user_id = true;

			_originalCreate_user_id = _create_user_id;
		}

		_create_user_id = create_user_id;
	}

	public long getOriginalCreate_user_id() {
		return _originalCreate_user_id;
	}

	@JSON
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	public void setStatus(String status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (_originalStatus == null) {
			_originalStatus = _status;
		}

		_status = status;
	}

	public String getOriginalStatus() {
		return GetterUtil.getString(_originalStatus);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Forum.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Forum toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Forum)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public Forum toUnescapedModel() {
		return (Forum)this;
	}

	@Override
	public Object clone() {
		ForumImpl forumImpl = new ForumImpl();

		forumImpl.setId_forum(getId_forum());
		forumImpl.setDescription(getDescription());
		forumImpl.setTimestamp(getTimestamp());
		forumImpl.setCompany_id(getCompany_id());
		forumImpl.setCreate_user_id(getCreate_user_id());
		forumImpl.setStatus(getStatus());

		forumImpl.resetOriginalValues();

		return forumImpl;
	}

	public int compareTo(Forum forum) {
		int value = 0;

		if (getId_forum() < forum.getId_forum()) {
			value = -1;
		}
		else if (getId_forum() > forum.getId_forum()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Forum)) {
			return false;
		}

		Forum forum = (Forum)obj;

		long primaryKey = forum.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ForumModelImpl forumModelImpl = this;

		forumModelImpl._originalTimestamp = forumModelImpl._timestamp;

		forumModelImpl._originalCompany_id = forumModelImpl._company_id;

		forumModelImpl._setOriginalCompany_id = false;

		forumModelImpl._originalCreate_user_id = forumModelImpl._create_user_id;

		forumModelImpl._setOriginalCreate_user_id = false;

		forumModelImpl._originalStatus = forumModelImpl._status;

		forumModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Forum> toCacheModel() {
		ForumCacheModel forumCacheModel = new ForumCacheModel();

		forumCacheModel.id_forum = getId_forum();

		forumCacheModel.description = getDescription();

		String description = forumCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			forumCacheModel.description = null;
		}

		Date timestamp = getTimestamp();

		if (timestamp != null) {
			forumCacheModel.timestamp = timestamp.getTime();
		}
		else {
			forumCacheModel.timestamp = Long.MIN_VALUE;
		}

		forumCacheModel.company_id = getCompany_id();

		forumCacheModel.create_user_id = getCreate_user_id();

		forumCacheModel.status = getStatus();

		String status = forumCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			forumCacheModel.status = null;
		}

		return forumCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{id_forum=");
		sb.append(getId_forum());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", timestamp=");
		sb.append(getTimestamp());
		sb.append(", company_id=");
		sb.append(getCompany_id());
		sb.append(", create_user_id=");
		sb.append(getCreate_user_id());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("net.appuntivari.forum.model.Forum");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_forum</column-name><column-value><![CDATA[");
		sb.append(getId_forum());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timestamp</column-name><column-value><![CDATA[");
		sb.append(getTimestamp());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>company_id</column-name><column-value><![CDATA[");
		sb.append(getCompany_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>create_user_id</column-name><column-value><![CDATA[");
		sb.append(getCreate_user_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Forum.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Forum.class };
	private long _id_forum;
	private String _description;
	private Date _timestamp;
	private Date _originalTimestamp;
	private long _company_id;
	private long _originalCompany_id;
	private boolean _setOriginalCompany_id;
	private long _create_user_id;
	private long _originalCreate_user_id;
	private boolean _setOriginalCreate_user_id;
	private String _status;
	private String _originalStatus;
	private long _columnBitmask;
	private Forum _escapedModel;
}