/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.appuntivari.forum.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ForumUser service. Represents a row in the &quot;PW_ForumUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.appuntivari.forum.model.impl.ForumUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.appuntivari.forum.model.impl.ForumUserImpl}.
 * </p>
 *
 * @author Pasturenzi Francesco
 * @see ForumUser
 * @see net.appuntivari.forum.model.impl.ForumUserImpl
 * @see net.appuntivari.forum.model.impl.ForumUserModelImpl
 * @generated
 */
public interface ForumUserModel extends BaseModel<ForumUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a forum user model instance should use the {@link ForumUser} interface instead.
	 */

	/**
	 * Returns the primary key of this forum user.
	 *
	 * @return the primary key of this forum user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this forum user.
	 *
	 * @param primaryKey the primary key of this forum user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_forum_user of this forum user.
	 *
	 * @return the id_forum_user of this forum user
	 */
	public long getId_forum_user();

	/**
	 * Sets the id_forum_user of this forum user.
	 *
	 * @param id_forum_user the id_forum_user of this forum user
	 */
	public void setId_forum_user(long id_forum_user);

	/**
	 * Returns the id_forum of this forum user.
	 *
	 * @return the id_forum of this forum user
	 */
	public long getId_forum();

	/**
	 * Sets the id_forum of this forum user.
	 *
	 * @param id_forum the id_forum of this forum user
	 */
	public void setId_forum(long id_forum);

	/**
	 * Returns the user_id of this forum user.
	 *
	 * @return the user_id of this forum user
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this forum user.
	 *
	 * @param user_id the user_id of this forum user
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the status of this forum user.
	 *
	 * @return the status of this forum user
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this forum user.
	 *
	 * @param status the status of this forum user
	 */
	public void setStatus(String status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ForumUser forumUser);

	public int hashCode();

	public CacheModel<ForumUser> toCacheModel();

	public ForumUser toEscapedModel();

	public ForumUser toUnescapedModel();

	public String toString();

	public String toXmlString();
}