/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.appuntivari.forum.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ForumPost service. Represents a row in the &quot;PW_ForumPost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.appuntivari.forum.model.impl.ForumPostModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.appuntivari.forum.model.impl.ForumPostImpl}.
 * </p>
 *
 * @author Pasturenzi Francesco
 * @see ForumPost
 * @see net.appuntivari.forum.model.impl.ForumPostImpl
 * @see net.appuntivari.forum.model.impl.ForumPostModelImpl
 * @generated
 */
public interface ForumPostModel extends BaseModel<ForumPost> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a forum post model instance should use the {@link ForumPost} interface instead.
	 */

	/**
	 * Returns the primary key of this forum post.
	 *
	 * @return the primary key of this forum post
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this forum post.
	 *
	 * @param primaryKey the primary key of this forum post
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_post of this forum post.
	 *
	 * @return the id_post of this forum post
	 */
	public long getId_post();

	/**
	 * Sets the id_post of this forum post.
	 *
	 * @param id_post the id_post of this forum post
	 */
	public void setId_post(long id_post);

	/**
	 * Returns the post of this forum post.
	 *
	 * @return the post of this forum post
	 */
	@AutoEscape
	public String getPost();

	/**
	 * Sets the post of this forum post.
	 *
	 * @param post the post of this forum post
	 */
	public void setPost(String post);

	/**
	 * Returns the timestamp of this forum post.
	 *
	 * @return the timestamp of this forum post
	 */
	public Date getTimestamp();

	/**
	 * Sets the timestamp of this forum post.
	 *
	 * @param timestamp the timestamp of this forum post
	 */
	public void setTimestamp(Date timestamp);

	/**
	 * Returns the user_id of this forum post.
	 *
	 * @return the user_id of this forum post
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this forum post.
	 *
	 * @param user_id the user_id of this forum post
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the id_category of this forum post.
	 *
	 * @return the id_category of this forum post
	 */
	public long getId_category();

	/**
	 * Sets the id_category of this forum post.
	 *
	 * @param id_category the id_category of this forum post
	 */
	public void setId_category(long id_category);

	/**
	 * Returns the id_post_parent of this forum post.
	 *
	 * @return the id_post_parent of this forum post
	 */
	public long getId_post_parent();

	/**
	 * Sets the id_post_parent of this forum post.
	 *
	 * @param id_post_parent the id_post_parent of this forum post
	 */
	public void setId_post_parent(long id_post_parent);

	/**
	 * Returns the user_id_post_parent of this forum post.
	 *
	 * @return the user_id_post_parent of this forum post
	 */
	public long getUser_id_post_parent();

	/**
	 * Sets the user_id_post_parent of this forum post.
	 *
	 * @param user_id_post_parent the user_id_post_parent of this forum post
	 */
	public void setUser_id_post_parent(long user_id_post_parent);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ForumPost forumPost);

	public int hashCode();

	public CacheModel<ForumPost> toCacheModel();

	public ForumPost toEscapedModel();

	public ForumPost toUnescapedModel();

	public String toString();

	public String toXmlString();
}