/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.appuntivari.forum.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Forum service. Represents a row in the &quot;PW_Forum&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.appuntivari.forum.model.impl.ForumModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.appuntivari.forum.model.impl.ForumImpl}.
 * </p>
 *
 * @author Pasturenzi Francesco
 * @see Forum
 * @see net.appuntivari.forum.model.impl.ForumImpl
 * @see net.appuntivari.forum.model.impl.ForumModelImpl
 * @generated
 */
public interface ForumModel extends BaseModel<Forum> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a forum model instance should use the {@link Forum} interface instead.
	 */

	/**
	 * Returns the primary key of this forum.
	 *
	 * @return the primary key of this forum
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this forum.
	 *
	 * @param primaryKey the primary key of this forum
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_forum of this forum.
	 *
	 * @return the id_forum of this forum
	 */
	public long getId_forum();

	/**
	 * Sets the id_forum of this forum.
	 *
	 * @param id_forum the id_forum of this forum
	 */
	public void setId_forum(long id_forum);

	/**
	 * Returns the description of this forum.
	 *
	 * @return the description of this forum
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this forum.
	 *
	 * @param description the description of this forum
	 */
	public void setDescription(String description);

	/**
	 * Returns the timestamp of this forum.
	 *
	 * @return the timestamp of this forum
	 */
	public Date getTimestamp();

	/**
	 * Sets the timestamp of this forum.
	 *
	 * @param timestamp the timestamp of this forum
	 */
	public void setTimestamp(Date timestamp);

	/**
	 * Returns the company_id of this forum.
	 *
	 * @return the company_id of this forum
	 */
	public long getCompany_id();

	/**
	 * Sets the company_id of this forum.
	 *
	 * @param company_id the company_id of this forum
	 */
	public void setCompany_id(long company_id);

	/**
	 * Returns the create_user_id of this forum.
	 *
	 * @return the create_user_id of this forum
	 */
	public long getCreate_user_id();

	/**
	 * Sets the create_user_id of this forum.
	 *
	 * @param create_user_id the create_user_id of this forum
	 */
	public void setCreate_user_id(long create_user_id);

	/**
	 * Returns the status of this forum.
	 *
	 * @return the status of this forum
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this forum.
	 *
	 * @param status the status of this forum
	 */
	public void setStatus(String status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Forum forum);

	public int hashCode();

	public CacheModel<Forum> toCacheModel();

	public Forum toEscapedModel();

	public Forum toUnescapedModel();

	public String toString();

	public String toXmlString();
}